name: Release Preview
on:
  pull_request:
    branches:
      - "*"
      - "!main"
    types: [auto_merge_enabled]

jobs:
  preview-bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Preview Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
